version: '3.3'
services:
  webgl:
    image: inclusionvalle/valle_magico_webgl_nginx:2.1.1
    container_name: valle_magico_game
    ports:
      - "8070:80"
    networks:
      - network-valle_magico
    depends_on:
      - valle_magico_back
    restart: always
    volumes:
      - "./docker/serverdata.json:/valle/StreamingAssets/serverdata.json"
  valle_magico_front:
    image: inclusionvalle/valle_magico_frontend:1.3.1
    container_name: valle_magico_front
    ports:
      - "9092:80"
    networks:
      - network-valle_magico
    depends_on:
      - valle_magico_back
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USERNAME=valle-user
      - DB_PASSWORD=Inclusionvalle2022*
      - DB_DATABASE=talentumehs_valle_magico
      - OPEN_LOCATION_DB=talentumehs_valle_open_location
      - BACKEND_URL="http://valle_magico_back:3000/"
  valle_magico_back:
    image: inclusionvalle/valle_magico_backend:1.1.0
    container_name: valle_magico_back
    ports:
      - "9091:3000"
    networks:
      - network-valle_magico
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USERNAME=valle-user
      - DB_PASSWORD=Inclusionvalle2022*
      - DB_ONE_NAME=talentumehs_valle_open_location
      - DB_TWO_NAME=talentumehs_valle_magico
networks:
  network-valle_magico:
    driver: bridge
